package com.mycompany.practica10.diu;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    private final JFileChooser fc; 
    DefaultListModel modeloArchivos = new DefaultListModel();
    
    public Interfaz() {
        initComponents();
        fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        listaArchivos.setModel(modeloArchivos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        elegirArchivosButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaArchivos = new javax.swing.JList<>();
        quitarSeleccionadosButton = new javax.swing.JButton();
        origenTxtField = new javax.swing.JTextField();
        destinoLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        comprimirButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        archivosComprimirjTxtArea = new javax.swing.JTextArea();
        origenLabel = new javax.swing.JLabel();
        destinoTxtField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuApp = new javax.swing.JMenu();
        itemCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        itemDescripción = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compresor de archivos");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivos en la carpeta"));

        elegirArchivosButton.setText("Elegir archivos");
        elegirArchivosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirArchivosButtonActionPerformed(evt);
            }
        });

        listaArchivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaArchivosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaArchivos);

        quitarSeleccionadosButton.setText("Quitar seleccionados");
        quitarSeleccionadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarSeleccionadosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(elegirArchivosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(quitarSeleccionadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elegirArchivosButton)
                    .addComponent(quitarSeleccionadosButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        origenTxtField.setEditable(false);

        destinoLabel.setText("Carpeta donde se guardará el .zip (Destino):");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivos a comprimir"));

        comprimirButton.setText("Empezar Compresión");
        comprimirButton.setEnabled(false);
        comprimirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprimirButtonActionPerformed(evt);
            }
        });

        archivosComprimirjTxtArea.setEditable(false);
        archivosComprimirjTxtArea.setColumns(20);
        archivosComprimirjTxtArea.setRows(5);
        jScrollPane3.setViewportView(archivosComprimirjTxtArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(comprimirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comprimirButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        origenLabel.setText("Carpeta seleccionada (Origen):");

        destinoTxtField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(origenTxtField)
                    .addComponent(origenLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(destinoLabel)
                    .addComponent(destinoTxtField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenLabel)
                    .addComponent(destinoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(origenTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinoTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        menuApp.setText("Aplicación");

        itemCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemCerrar.setText("Cerrar aplicación");
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuApp.add(itemCerrar);

        jMenuBar1.add(menuApp);

        jMenu2.setText("Ayuda");

        jMenu1.setText("Acerca de");

        itemDescripción.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemDescripción.setText("Descripción");
        itemDescripción.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDescripciónActionPerformed(evt);
            }
        });
        jMenu1.add(itemDescripción);

        jMenu2.add(jMenu1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elegirArchivosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirArchivosButtonActionPerformed
        int option = fc.showOpenDialog(this);
        if(JFileChooser.APPROVE_OPTION == option){
            modeloArchivos.removeAllElements();
            archivosComprimirjTxtArea.setText("");
            destinoTxtField.setText("");
            comprimirButton.setEnabled(false);
            File file = fc.getSelectedFile();
            origenTxtField.setText(file.getPath());
            for (File filename : file.listFiles()){
                if(filename.isFile()) modeloArchivos.addElement(filename.getPath());
            }
            listaArchivos.setModel(modeloArchivos);
        }
    }//GEN-LAST:event_elegirArchivosButtonActionPerformed

    private void listaArchivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaArchivosValueChanged
        String texto = "";
        if(evt.getValueIsAdjusting()){
            int[] selectedIndices = listaArchivos.getSelectedIndices();
            for (int index : selectedIndices) {
                texto += modeloArchivos.getElementAt(index).toString() + "\n";
                archivosComprimirjTxtArea.setText(texto);
                comprimirButton.setEnabled(true);
            }
            
        }
    }//GEN-LAST:event_listaArchivosValueChanged

    private void quitarSeleccionadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarSeleccionadosButtonActionPerformed
        listaArchivos.clearSelection();
        archivosComprimirjTxtArea.setText("");
        comprimirButton.setEnabled(false);
    }//GEN-LAST:event_quitarSeleccionadosButtonActionPerformed

    private void comprimirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprimirButtonActionPerformed
        int option = fc.showSaveDialog(this);
        if(JFileChooser.APPROVE_OPTION == option) {
            crearZip(fc.getSelectedFile().getPath());
            destinoTxtField.setText(fc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_comprimirButtonActionPerformed

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        int answer = JOptionPane.showConfirmDialog(this, "¿Quiere cerrar la aplcación?", "Salir", JOptionPane.YES_NO_OPTION);
        if(answer == JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemDescripciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDescripciónActionPerformed
        JOptionPane.showMessageDialog(this, "Esta aplicación sirve para comprimir ficheros."
                + " El usuario selecciona una carpeta de su ordenador y la aplicación le muestra los ficheros"
                + " disponibles que puede comprimir.\n"
                + "Realizado por: Borja Álvarez Medina y Esther Zurita Curbelo", "Ayuda: Descripción de la Aplicación", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemDescripciónActionPerformed

    private void crearZip(String directory) {
        List<String> files = new ArrayList<String>();
        String[] filesToCompress = archivosComprimirjTxtArea.getText().split("\n");
        files.addAll(Arrays.asList(filesToCompress));
        ZipUI zipUI = new ZipUI(files, directory);
        zipUI.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea archivosComprimirjTxtArea;
    private javax.swing.JButton comprimirButton;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JTextField destinoTxtField;
    private javax.swing.JButton elegirArchivosButton;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemDescripción;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaArchivos;
    private javax.swing.JMenu menuApp;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JTextField origenTxtField;
    private javax.swing.JButton quitarSeleccionadosButton;
    // End of variables declaration//GEN-END:variables
}
